artifact_root: 'artifact'

data_ingestion:
  encrypted_dataset: ATLAS_R2.0_encrypted.tar.gz
  zip_dataset: Raw.tar.gz
  unzip_dir: artifact/
  secret_dir: secret.yaml

data_validation:
  root_dir: artifact/data_ingestion
  sample_op_dir: artifact/data_validation
  animation_file: artifact/data_validation/mri_animation.mp4
  report_file: artifact/data_validation/report.csv

data_preprocessing:
  root_dir: artifact/data_preprocessed
  training_data: artifact/data_ingestion/Training
  testing_data: artifact/data_ingestion/Testing
  train_csv: artifact/data_preprocessed/train.csv
  test_csv: artifact/data_preprocessed/test.csv
  preprocess_train_in: artifact/data_preprocessed/Training/input
  preprocess_train_op: artifact/data_preprocessed/Training/output
  preprocess_test_in: artifact/data_preprocessed/Testing/input